name: Delete All Old Actions Runs

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old runs
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          CURRENT: ${{ github.run_id }}
        run: |
          gh api --paginate \
            -H "Accept: application/vnd.github+json" \
            "/repos/$REPO/actions/runs?per_page=100" \
            --jq '.workflow_runs[].id' |
          while read ID; do
            if [ "$ID" != "$CURRENT" ]; then
              echo "Deleting $ID"
              gh api --method DELETE \
                "/repos/$REPO/actions/runs/$ID" || true
            fi
          done
